Customer-Selfservice-App/force-app/main/default/objects/Dish__c/Dish__c.object-meta.xml
<CustomObject>
    <label>Dish</label>
    <nameField>
        <label>Dish Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Customer-Selfservice-App/force-app/main/default/objects/Dish_Order__c/Dish_Order__c.object-meta.xml
<CustomObject>
    <label>Dish Order</label>
    <nameField>
        <label>Dish_Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dish orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Customer-Selfservice-App/force-app/main/default/objects/Dish_Order__c/fields/Dish__c.field-meta.xml
<CustomField>
    <fullName>Dish__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dish</label>
    <referenceTo>Dish__c</referenceTo>
    <relationshipName>Dish_orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Customer-Selfservice-App/force-app/main/default/objects/Dish_Order__c/fields/Dish_Count__c.field-meta.xml
<CustomField>
    <fullName>Dish_Count__c</fullName>
    <label>Dish Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Customer-Selfservice-App/force-app/main/default/objects/Dish_Order__c/fields/Item_Order__c.field-meta.xml
<CustomField>
    <fullName>Item_Order__c</fullName>
    <label>Item Order</label>
    <referenceTo>Item_Order__c</referenceTo>
    <relationshipLabel>Dish orders</relationshipLabel>
    <relationshipName>Dish_orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Customer-Selfservice-App/force-app/main/default/objects/Item_Order__c/Item_Order__c.object-meta.xml
<CustomObject>
    <label>Item Order</label>
    <nameField>
        <label>Item Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Customer-Selfservice-App/force-app/main/default/objects/Item_Order__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Address__c</fullName>
    <label>Delivery Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Customer-Selfservice-App/force-app/main/default/objects/Item_Order__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_status</valueSetName>
    </valueSet>
</CustomField>

Customer-Selfservice-App/force-app/main/default/globalValueSets/Delivery_status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ordered</fullName>
    </customValue>
    <customValue>
        <fullName>In processing</fullName>
    </customValue>
    <customValue>
        <fullName>Ready</fullName>
    </customValue>
    <customValue>
        <fullName>In deliver</fullName>
    </customValue>
    <customValue>
        <fullName>Delivered</fullName>
    </customValue>
    <masterLabel>Delivery status</masterLabel>
</GlobalValueSet>

Customer-Selfservice-App/force-app/main/default/classes/DishOrderController.cls
public with sharing class DishOrderController {
	@AuraEnabled
    public static string makeOrder (Decimal totalPrice, String deliveryAddress) {
        Date orderDate = System.today();
        String status = 'Ordered';
        Item_Order__c order = new Item_Order__c (Total_Price__c = totalPrice,
                                           Delivery_Address__c = deliveryAddress,
                                           Delivery_Status__c = status,
                                           Order_Date__c = orderDate);
        insert order;
        return order.Id;
    }

    @AuraEnabled
    public static void addDishToOrder (String orderId,
                                       String dishId,
                                       String dishComment,
                                       Integer dishCount) {
    	Dish_Order__c dishOrder = new Dish_Order__c();
		dishOrder.Item_Order__c = orderId;
		dishOrder.Dish__c = dishId;
		dishOrder.Comment__c = dishComment;
		dishOrder.Dish_Count__c = dishCount;
		insert dishOrder;
	}

    @AuraEnabled (Cacheable = true)
    public static List<Item_Order__c> getOrders() {
        Id currentUser = UserInfo.getUserId();
        return [SELECT Id, Name, Order_Date__c, Delivery_Status__c, Total_Price__C, Delivery_Address__c, (SELECT Dish__r.Name FROM Dish_Orders__r)
                FROM Item_Order__c
                WHERE OwnerId = :currentUser
                ORDER BY Order_Date__c DESC];
    }
}